language: java
jdk:
 - oraclejdk8

cache:
  directories:
    - $HOME/.m2

before_install:
 - chmod +x gradlew

install: true
script:
  - ./gradlew clean install
  
after_success:
  - bash <(curl -s https://codecov.io/bash) -t 01570e5d-c6fc-4737-b7cd-0c6c5cbe2178
